### ISSUE TITLE
Vagrantfile doesn't enable LIO support

### ISSUE THREAD

**Issue by philp** [storageos/storageos.github.io#163]
After starting up a cluster of VMs using the supplied Vagrantfile, they are unable to communicate properly, with the container constantly restarting because of bad health.

Enabling LIO as per the instructions at https://docs.storageos.com/docs/reference/os_support fixes things. Does this need to be added as part of the provisioning script?

**Comment by oicheryl** [comment]
Hi @philp, I've just merged in the fix for this. Thanks for reporting!
